[2023-01-27 17:35:25] (DEBUG) => ConnectionError((<urllib3.connection.HTTPConnection object at 0x7fc2f840e910>, 'Connection to 221.157.125.36 timed out. (connect timeout=30)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7fc2f840e910>, 'Connection to 221.157.125.36 timed out. (connect timeout=30)'))
